### ISSUE TITLE
Incomplete porting

### ISSUE THREAD

**Issue by piotrtomiak** [angelozerr/minimatch.java#1]
@angelozerr in MyEclipse we have used JSDT code for matching the path patterns, which worked quite well for us. I am wondering whether we should switch to use Minimatch. It looks promising, however it fails with some very basic tests from original minimatch, e.g. "b*/" matches not only "bdir/", but also "b", "bac", etc.

My concern is that users could blow up the code by inputing an untested pattern. Could you explain how much of the porting has been done, and what areas need further improvements?

**Comment by angelozerr** [comment]
> It looks promising, however it fails with some very basic tests from original minimatch, e.g. "b*/" matches not only "bdir/", but also "b", "bac", etc.

That's strange `Minimatch.minimatch("b", "b*/", options)` returns true, no? Perhaps it's the use of minimatch.java which is not well integrated?

At first I have decided to port minimatch in Java because it is a lot of used in node.js context. Today tern.java uses JSDT pattern, but you can add your own pattern inside .tern-project (to write more complex pattern than JSDT).

> My concern is that users could blow up the code by inputing an untested pattern. 

You can find Java tests at https://github.com/angelozerr/minimatch.java/tree/master/src/test/java/minimatch

and you can find HTML page https://github.com/angelozerr/minimatch.java/tree/master/html which shows result of minimatch in JavaScript context.

> Could you explain how much of the porting has been done, and what areas need further improvements?

With awful mean. I have copied/pasted the minimatch.js in my Java project and translate it to Java, but it seems that there are some bugs? The expand feature is not supported too.

I hope I will have a lot of contribution to improve minimatch.java and have a commons like library which support wildcard (powerful wildcard).

For tern.java integration in MyEclipse, there are 2 options:
- use minimatch.java and improve it to fix bugs.
- provides an extension point which gives the capability to choose the include/exclude patterns (we will able to implement with JSDT and Minimatch and for the moment activate JSDT once minimatch will be more stable?)

**Comment by piotrtomiak** [comment]
> That's strange Minimatch.minimatch("b", "b*/", options) returns true, no? Perhaps it's the use of minimatch.java which is not well integrated?

Yes, it looks to support the cases you were interested the most, but it fails to conform to all the requirements set up by original minimatch/bash. 

> Today tern.java uses JSDT pattern

As I looked through JSDT code, it converts "foo/" to "foo/**" before matching, assuming that user wanted to include all the contents from the folder. I haven't found that translation in your code, might be good to add it in "toTernPatterns" method.

> For tern.java integration in MyEclipse

I am patching Tern.java, so we don't need ext-points. However, I want the patterns to be compatible, so that users do not experience issues when migrating to MyEclipse. I guess you're willing to stay with Minimatch and improve the support, instead of using a simplified version. In such a case I will work on ensuring that all the tests from original minimatch pass, except for the tests which do not apply, e.g. the expanding ones.

**Comment by angelozerr** [comment]
> As I looked through JSDT code, it converts "foo/" to "foo/**" before matching, assuming that user wanted to include all the contents from the folder. I haven't found that translation in your code, might be good to add it in "toTernPatterns" method.

Sorry I don't remember with that -(

> However, I want the patterns to be compatible, so that users do not experience issues when migrating to MyEclipse.

Today the only available UI to define inclusion/exclusion pattern is JSDT. So the pattern matches JSDT. User can add in the .tern-project at hand the pattern (with minimatch format), but I have not spoken about that in the wiki (I think none users do that).

>  I guess you're willing to stay with Minimatch and improve the support, instead of using a simplified version. 

Yes I would like to do that.

> In such a case I will work on ensuring that all the tests from original minimatch pass, except for the tests which do not apply, e.g. the expanding ones.

You speak about JSDT or improve minimatch? With MyEclipse you wish to keep JSDT inclusion/exclusion and not use minimatch, is that?

**Comment by piotrtomiak** [comment]
> So the pattern matches JSDT.

AFAIK, there is no validation for the pattern in JSDT UI, so user can input anything. And that anything will be matched using minimatch. So we need to be careful.

> You speak about JSDT or improve minimatch? With MyEclipse you wish to keep JSDT inclusion/exclusion and not use minimatch, is that?

I will work on improving minimatch. Right now, I am translating all the tests from Isaacs minimatch. Not bad, so far 8 fails from 52 runs.

**Comment by angelozerr** [comment]
> So we need to be careful.

Ok I understand.

> I will work on improving minimatch. Right now, I am translating all the tests from Isaacs minimatch. Not bad, so far 8 fails from 52 runs.

It means that you wish to contribute to minimatch.java? If it that it's very cool! I have a lot of ideas too for those include/exclude pattern liek use it with bower.json (ignore files), jshint. And a very important this is to create tests inside tern.java which uses minimatch https://github.com/angelozerr/tern.java/issues/299 (for validation where it is managed with WTP and completion which is managed by IResourceVistor)

**Comment by angelozerr** [comment]
@piotrtomiak I think I can close this issue?

**Comment by piotrtomiak** [comment]
right, forgot to reference it in commits
